name: oodaa_messenger
description: A fully private, peer-to-peer messaging app with zero cloud storage and end-to-end encryption.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.6
  
  # WebRTC for P2P communication
  flutter_webrtc: ^0.11.7
  
  # Local storage and encryption
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # Cryptography
  cryptography: ^2.5.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  
  # QR Code functionality
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7
  
  # Nearby connections and Bluetooth
  nearby_connections: ^4.3.0
  flutter_bluetooth_serial: ^0.4.0
  
  # File handling and media
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  image: ^4.1.3
  
  # UI and utilities
  provider: ^6.1.1
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  local_auth: ^2.1.7
  
  # Network and WebSocket
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # TODO: Add app icons and splash screens
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # TODO: Add custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
